name: Generate CV

on:
  push:
    branches:
      - main  # Cambiar esto hay otra rama principal

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Paso 1: Clonar el repositorio
      - name: Checkout code
        uses: actions/checkout@v3

      # Paso 2: Instalar Pandoc y sus dependencias
      - name: Install Pandoc and dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc texlive-xetex texlive-fonts-recommended

      # Paso 3: Generar el archivo PDF desde Markdown
      - name: Generate PDF
        run: |
          pandoc cv/cv.md --template=templates/template.tex --pdf-engine=xelatex -o cv/Cristina_Fuentes_CV.pdf

      # Paso 4: Generar el archivo DOCX desde Markdown
      - name: Generate DOCX
        run: |
          pandoc cv/cv.md --reference-doc=templates/template.docx -o cv/Cristina_Fuentes_CV.docx

      # Paso 5: Subir los archivos generados al repositorio
      - name: Commit and push updated CV files
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --local user.name "GitHub Actions"
          git config --local user.email "actions@github.com"
          git add cv/Cristina_Fuentes_CV.pdf cv/Cristina_Fuentes_CV.docx
          git commit -m "Updated CV files" || echo "No changes to commit"
          git push
